// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYyrqjYbffYF7-P-zx0qIvni3nCeCvUG8',
    appId: '1:1031116904139:web:f6afd3fbd7eaba55d7ed4e',
    messagingSenderId: '1031116904139',
    projectId: 'studentatt-001',
    authDomain: 'studentatt-001.firebaseapp.com',
    storageBucket: 'studentatt-001.firebasestorage.app',
    measurementId: 'G-LHJ7TKD503',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXY0nvB76JJyi7bnogkWPZ-BdZrCClZU',
    appId: '1:1031116904139:android:95fdaacfbf34a809d7ed4e',
    messagingSenderId: '1031116904139',
    projectId: 'studentatt-001',
    storageBucket: 'studentatt-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJauKoGQmVwf1GDY7gD5orgcUDQWQ9aBQ',
    appId: '1:1031116904139:ios:d9ce73c0b5473eded7ed4e',
    messagingSenderId: '1031116904139',
    projectId: 'studentatt-001',
    storageBucket: 'studentatt-001.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJauKoGQmVwf1GDY7gD5orgcUDQWQ9aBQ',
    appId: '1:1031116904139:ios:d9ce73c0b5473eded7ed4e',
    messagingSenderId: '1031116904139',
    projectId: 'studentatt-001',
    storageBucket: 'studentatt-001.firebasestorage.app',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYyrqjYbffYF7-P-zx0qIvni3nCeCvUG8',
    appId: '1:1031116904139:web:89689cd6bfda01bfd7ed4e',
    messagingSenderId: '1031116904139',
    projectId: 'studentatt-001',
    authDomain: 'studentatt-001.firebaseapp.com',
    storageBucket: 'studentatt-001.firebasestorage.app',
    measurementId: 'G-KMSTPX409L',
  );
}
